### ISSUE TITLE
switch to store charms and bundles

### ISSUE THREAD

**Issue by merlijn-sebrechts** [tengu-team/tengu-browser#13]
Everything can be found here: https://jujucharms.com/u/tengu-bot/

**normal bundles**

Storm and spark are now called "microbatch" and "streaming" (bundles can't have the same name as a charm).

```
https://api.jujucharms.com/charmstore/v5/~tengu-bot/<bundle-name>/archive/bundle.yaml
```

**hauchiwa bundle**

```
https://api.jujucharms.com/charmstore/v5/~tengu-bot/sojobo/archive/hauchiwa.yaml.template
```

**Comment by gvseghbr** [comment]
done for 'openID-connect' branche.

**Comment by gvseghbr** [comment]
merge with openID-connect branche is done.
