### ISSUE TITLE
add id-token header to get modelinfo

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/tengu-browser#17]

**Comment by LeandroOrdonez** [comment]
I'm getting an error in creating the Hauchiwa when running `:tengu model create microbatch`, and there is an error message in the browser console saying:

`XMLHttpRequest cannot load http://193.190.127.184:29035/sojobo13/. Request header field id-token is not allowed by Access-Control-Allow-Headers in preflight response.`

I guess it has to do with this issue, right?

**Comment by gvseghbr** [comment]
Similar problem, but diferent place. I'll create a specific _issue_ for this.
Thanks for spotting it.
