### ISSUE TITLE
Cannot find root certificate for credential signer

### ISSUE THREAD

**Issue by merlijn-sebrechts** [tengu-team/tengu-browser#19]
h-uxtest2 failed because of the following error:

```
u'NOT_PARSED': u'',
 u'is_exit_code_error': True,
 u'json_output': {u'code': 3,
                  u'output': u'Cannot find root certificate for credential signer',
                  u'protogeni_error_log': u'urn:publicid:IDN+wall2.ilabt.iminds.be+log+d542909c31174924e8c962adf659c941',
                  u'protogeni_error_url': u'https://www.wall2.ilabt.iminds.be/spewlogfile.php3?logfile=d542909c31174924e8c962adf659c941',
                  u'value': 0},
 u'large_error': u'Error retrieving user credential',
 u's4cred': u'urn:publicid:IDN+wall2.ilabt.iminds.be+user+tvanhove'}
```

Full error: https://www.wall2.ilabt.iminds.be/spewlogfile.php3?logfile=d542909c31174924e8c962adf659c941

This seems to be a problem with all hauchiwa's that thomas created.

**Comment by merlijn-sebrechts** [comment]
@tvanhove should be able to solve it by changing his password (changing it to he same value should work) on the authority website. From then on all newly created hauchiwa's shouldn't have this problem anymore

**Comment by gvseghbr** [comment]
How can we fix this in a more sustainable way?
- Better error messages from the backend
- Put a limit on the cookie used for AuthZ
- Make sure the AuthZ credentials saved in the hauchiwa are changed when a new version of the credentials are pushed to the backend (this also means that we should push the credentials to the backend

But, anyway, most of this won't be a problem anymore if we shift towards MAAS ;)

**Comment by merlijn-sebrechts** [comment]
I think it's just not worth it, since I still hope to one day retire the
jfed/emulab backend..

Op woensdag 12 oktober 2016 heeft Gregory Van Seghbroeck <
notifications@github.com> het volgende geschreven:
