### ISSUE TITLE
Properly show unknown topologies

### ISSUE THREAD

**Issue by merlijn-sebrechts** [tengu-team/tengu-browser#2]
If a topology contains parts that are not specified in the "higher level bundle", they should be shown as just dots with bidirectional relationships.

**Comment by gvseghbr** [comment]
As a 1st step, I would suggest to make a distinction between (i) models created via the UI's built-in models and (ii) models created manually by the user (e.g. via the juju-ui). For (i) we show it as it is now, with the 'logical' nodes as wel. For (ii) we show all the services and the relationships as they are defined in the model (at this moment equivalent to a juju bundle). So, we don't try to map clusters of services to logical nodes. When a model does not strictly follow a built-in model, it is shown as in (ii).

**Comment by merlijn-sebrechts** [comment]
That seems like a good 1st step. I think a lot of people will follow the workflow of "start with a bundle and then build on top of it". That's why I think it would be good to also show other charms.
