### ISSUE TITLE
New possible states of hauchiwa

### ISSUE THREAD

**Issue by merlijn-sebrechts** [tengu-team/tengu-browser#7]
With the new way of Hauchiwa status reporting, there are a few changes. A Hauchiwa will show port-forwards from the moment the Hauchiwa API is available. This means that the Hauchiwa can have workload-state `active` before the model is ready.

What might be best is to have the `:tengu hauchiwa status` command show "model is not ready yet, please wait" when the Hauchiwa has no models.

**Comment by gvseghbr** [comment]
Hauchiwa level was removed.
